### ISSUE TITLE
to use

### ISSUE THREAD

**Issue by docmarcus** [rutube/RutubePlaylist#1]
Hello i am french, i do not understand how to add several videos to compose a playlist?

**Comment by igorpetrov** [comment]
Hello!

We're sorry that you are having problems with Rutube API.

This kind of playlist were designed for play predefined sets of content, such as Tags, Users, TV shows etc. So you can't compose playlist with whatever video.

The only option I see is to create a user, and knowing its ID use its videos in this playlist:

```json
{
    "feeds": [
        { "id": "USER_ID", "type": "user" }
    ]
}
```

But it's dirty hack for your case, of course.
